Integration_Examples/Inbound_Mexichem/objects/IntegrationMap__c.object
<CustomObject>
    <description>[a09][IntegrationMap__c] Mapa de integração.</description>
    <fields>
        <fullName>CommandClassName__c</fullName>
        <defaultValue>&quot;GenericIntegrationService&quot;</defaultValue>
        <label>Classe de comando</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DMLOperationTxt__c</fullName>
        <label>Operação</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Insert</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Upsert</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntegrationId__c</fullName>
        <label>ID da integração</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OutputDataTypeTxt__c</fullName>
        <label>Tipo de dado de entrada</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CSV</fullName>
                </value>
                <value>
                    <fullName>JSON</fullName>
                    <default>true</default>
                    <label>JSON</label>
                </value>
                <value>
                    <fullName>XML</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SObjectApiNameTxt__c</fullName>
        <label>API name do objeto</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Mapa de integração</label>
    <nameField>
        <label>Integração</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapas de integração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/objects/IntegrationMapItem__c.object
<CustomObject>
    <description>[a08][IntegrationMapItem__c] Mapa de integração item.</description>
    <fields>
        <fullName>ExternalFieldNameTxt__c</fullName>
        <label>Campo externo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntegrationMap__c</fullName>
        <label>Mapa de integração</label>
        <referenceTo>IntegrationMap__c</referenceTo>
        <relationshipLabel>Mapa de integração items</relationshipLabel>
        <relationshipName>IntegrationMapItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>InternalFieldNameTxt__c</fullName>
        <label>Campo interno</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTxt__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Decimal</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>Lookup Formula</fullName>
                </value>
                <value>
                    <fullName>String</fullName>
                    <default>true</default>
                    <label>String</label>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Mapa de integração item</label>
    <nameField>
        <displayFormat>ITI-{000000000}</displayFormat>
        <label>Nome de Mapa de integração item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapa de integração items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/classes/ZTinteg_CSVTransformer.cls
@isTest
private class ZTinteg_CSVTransformer
{
    static testMethod void testAll()
    {
    	// Prepare test data
    	IntegrationMap__c integrationMap = ULTestData.createIntegrationMap('Integração XXX', 'Contact', 'GenericIntegrationService', 'eventName', 'Insert', '', 'CSV');
    	insert integrationMap;
    	
    	IntegrationMapItem__c integrationMapItem1 = ULTestData.createIntegrationMapItem(integrationMap.Id, 'Name', 'XPTO_NAME', 'String');
    	insert integrationMapItem1;
    	
    	Queue__c queue = ULTestData.createQueue(integrationMap.Id, 'eventName', '99');
    	insert queue;
    	
    	String csvData = '1;2;3;4;5;6;7';
    	
    	// Start Test
		System.Test.startTest();
		
    	integ_CSVTransformer csvTransformer = new integ_CSVTransformer();
    	
    	List<SObject> test01 = csvTransformer.convertToSObjectList(integrationMap, csvData);
    	
    	String test02 = csvTransformer.convertToRawData(new List<SObject>{queue});
    	
    	// Stop Test
		System.Test.stopTest();
		
		// Verify data
		System.assert(csvTransformer != null);
    }
    
    public static testmethod void contactImportCSV(){
        
        IntegrationMap__c integ = new IntegrationMap__c(
        	Name = 'Integ Contact CSV',
            IntegrationId__c = 'SYNC_CONTACT_INBOUND',
            SObjectApiNameTxt__c = 'Contact',
            DMLOperationTxt__c = 'Insert',
            CommandClassName__c = 'GenericIntegrationService',
            OutputDataTypeTxt__c  = 'CSV'
        );
        insert integ;
        
        IntegrationMapItem__c integItem = new IntegrationMapItem__c(
            IntegrationMap__c = integ.Id,
            TypeTxt__c  = 'String',
            InternalFieldNameTxt__c = 'LastName',
            ExternalFieldNameTxt__c = '3'//index col number
        );
        insert integItem;
        
        WSInBoundOrquestration.WSInBoundOrquestrationVO vo = new WSInBoundOrquestration.WSInBoundOrquestrationVO();
        vo.integrationId = 'SYNC_CONTACT_INBOUND';
        vo.content = 'Dief, Quadros, OK, 02';
        vo.isSync = true;
        
        WSInBoundOrquestration.executePost(vo);
        
        integ_CSVTransformer transf = new integ_CSVTransformer();
        transf.convertToRawData(new List<Contact>{});
        
    }
    
}