Integration_Examples/Inbound_Mexichem/objects/IntegrationMapItem__c.object
<CustomObject>
    <description>[a08][IntegrationMapItem__c] Mapa de integração item.</description>
    <fields>
        <fullName>ExternalFieldNameTxt__c</fullName>
        <label>Campo externo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapa de integração item</label>
    <nameField>
        <displayFormat>ITI-{000000000}</displayFormat>
        <label>Nome de Mapa de integração item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapa de integração items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/classes/integ_OrderItemStatus.cls
public with sharing class integ_OrderItemStatus implements IFormulaField {
	public Object resolve(IntegrationMapItem__c item, Map<String, Object> externalDataMap) {
        String aux = (String)externalDataMap.get(item.ExternalFieldNameTxt__c);
        String fatAmtStr = (String)externalDataMap.get('RFMNG');
        Decimal fatAmt = fatAmtStr != null ? Decimal.valueOf(fatAmtStr.trim()) : 0;
        String orderStatus = (String)externalDataMap.get('STATV2');
        if(orderStatus == 'Processado completamente') return 'ENTREGUE';
        if(fatAmt != 0) return 'FATURADO';
        if(aux == 'REPOSIÇÃO' || aux == 'REPOSICAO' || aux == 'SUBSTITUICAO' || aux == 'SUBSTITUIÇÃO') return null;
        return aux;
	}
}