Integration_Examples/Inbound_Mexichem/objects/IntegrationMap__c.object
<CustomObject>
    <description>[a09][IntegrationMap__c] Mapa de integração.</description>
    <fields>
        <fullName>CommandClassName__c</fullName>
        <defaultValue>&quot;GenericIntegrationService&quot;</defaultValue>
        <label>Classe de comando</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomOperationClassName__c</fullName>
        <label>Nome da classe da operação customizada</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DMLOperationTxt__c</fullName>
        <label>Operação</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Insert</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Upsert</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntegrationId__c</fullName>
        <label>ID da integração</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OutputDataTypeTxt__c</fullName>
        <label>Tipo de dado de entrada</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CSV</fullName>
                </value>
                <value>
                    <fullName>JSON</fullName>
                    <default>true</default>
                    <label>JSON</label>
                </value>
                <value>
                    <fullName>XML</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SObjectApiNameTxt__c</fullName>
        <label>API name do objeto</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Mapa de integração</label>
    <nameField>
        <label>Integração</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapas de integração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/objects/IntegrationMapChild__c.object
<CustomObject>
    <description>[a07][IntegrationMapChild__c] Mapa da integração filha.</description>
    <fields>
        <fullName>ChildLkp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mapa de integração</label>
        <referenceTo>IntegrationMap__c</referenceTo>
        <relationshipLabel>Mapa da integração filha (Mapa de integração)</relationshipLabel>
        <relationshipName>Mapa_da_integra_o_filha</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderNmb__c</fullName>
        <label>Ordem</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ParentLkp__c</fullName>
        <label>Mapa de integração</label>
        <referenceTo>IntegrationMap__c</referenceTo>
        <relationshipLabel>Mapa da integração filha</relationshipLabel>
        <relationshipName>IntegratioMapParents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Mapa da integração filha</label>
    <nameField>
        <label>Nome de Mapa da integração filha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapa da integração filha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/objects/IntegrationMapItem__c.object
<CustomObject>
    <description>[a08][IntegrationMapItem__c] Mapa de integração item.</description>
    <fields>
        <fullName>DefaultValueTxt__c</fullName>
        <label>Valor padrão</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalFieldNameTxt__c</fullName>
        <label>Campo externo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FormulaClassName__c</fullName>
        <label>Nome da classe da fórmula</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntegrationMap__c</fullName>
        <label>Mapa de integração</label>
        <referenceTo>IntegrationMap__c</referenceTo>
        <relationshipLabel>Mapa de integração items</relationshipLabel>
        <relationshipName>IntegrationMapItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>InternalFieldNameTxt__c</fullName>
        <label>Campo interno</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>É ativo?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRequired__c</fullName>
        <defaultValue>true</defaultValue>
        <label>É obrigatório?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RelatedObjectExternalIdTxt__c</fullName>
        <label>Id externo do objeto relacionado</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTxt__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Decimal</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>Lookup Formula</fullName>
                </value>
                <value>
                    <fullName>String</fullName>
                    <default>true</default>
                    <label>String</label>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Mapa de integração item</label>
    <nameField>
        <displayFormat>ITI-{000000000}</displayFormat>
        <label>Nome de Mapa de integração item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapa de integração items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/classes/IntegrationMapDAO.cls
public with sharing class IntegrationMapDAO {
	
	public static List<IntegrationMap__c> getAll() {
		return [
			SELECT Id, Name, DMLOperationTxt__c, SObjectApiNameTxt__c, CommandClassName__c, IntegrationId__c, CustomOperationClassName__c, OutputDataTypeTxt__c,
			(SELECT Id, Name, IsRequired__c, DefaultValueTxt__c, ExternalFieldNameTxt__c, InternalFieldNameTxt__c, TypeTxt__c, RelatedObjectExternalIdTxt__c, FormulaClassName__c, IsActive__c FROM IntegrationMapItems__r ORDER BY NAME), 
			(SELECT Id, Name, ParentLkp__c, ChildLkp__c, ChildLkp__r.IntegrationId__c FROM IntegratioMapParents__r ORDER BY OrderNmb__c) 
			FROM IntegrationMap__c
			LIMIT 100
		];
	}
    
}