Integration_Examples/Inbound_Mexichem/objects/IntegrationMapItem__c.object
<CustomObject>
    <description>[a08][IntegrationMapItem__c] Mapa de integração item.</description>
    <fields>
        <fullName>FormulaClassName__c</fullName>
        <label>Nome da classe da fórmula</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InternalFieldNameTxt__c</fullName>
        <label>Campo interno</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedObjectExternalIdTxt__c</fullName>
        <label>Id externo do objeto relacionado</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTxt__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Decimal</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>Lookup Formula</fullName>
                </value>
                <value>
                    <fullName>String</fullName>
                    <default>true</default>
                    <label>String</label>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Mapa de integração item</label>
    <nameField>
        <displayFormat>ITI-{000000000}</displayFormat>
        <label>Nome de Mapa de integração item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapa de integração items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/classes/ZTinteg_FieldCastLookupFormula.cls
@isTest
private class ZTinteg_FieldCastLookupFormula {
    static testMethod void testAll() {

		Schema.sObjectType sObjectType = Schema.getGlobalDescribe().get('Order__c');

		Map <String, Schema.SObjectField> sObjectFieldMap = sObjectType.getDescribe()
																.fields
																.getMap();
        
        IntegrationMapItem__c it = new IntegrationMapItem__c(
            InternalFieldNameTxt__c = 'CaseLkp__c',
            RelatedObjectExternalIdTxt__c = 'CustomIDTxt__c',
            FormulaClassName__c = 'integ_OrderCaseFormula',
            TypeTxt__c = 'Lookup Formula'
        );
        
        integ_FieldCastLookupFormula f = new integ_FieldCastLookupFormula();
        f.getValue(sObjectFieldMap, new Map<String, Object>{
            'CASOSALESFORCE' => 1
        }, it, '');
        
    }
}