Integration_Examples/Inbound_Mexichem/objects/IntegrationMap__c.object
<CustomObject>
    <description>[a09][IntegrationMap__c] Mapa de integração.</description>
    <fields>
        <fullName>SObjectApiNameTxt__c</fullName>
        <label>API name do objeto</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Mapa de integração</label>
    <nameField>
        <label>Integração</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapas de integração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/objects/IntegrationMapItem__c.object
<CustomObject>
    <description>[a08][IntegrationMapItem__c] Mapa de integração item.</description>
    <fields>
        <fullName>DefaultValueTxt__c</fullName>
        <label>Valor padrão</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalFieldNameTxt__c</fullName>
        <label>Campo externo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntegrationMap__c</fullName>
        <label>Mapa de integração</label>
        <referenceTo>IntegrationMap__c</referenceTo>
        <relationshipLabel>Mapa de integração items</relationshipLabel>
        <relationshipName>IntegrationMapItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>InternalFieldNameTxt__c</fullName>
        <label>Campo interno</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>É ativo?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRequired__c</fullName>
        <defaultValue>true</defaultValue>
        <label>É obrigatório?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TypeTxt__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Decimal</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>Lookup Formula</fullName>
                </value>
                <value>
                    <fullName>String</fullName>
                    <default>true</default>
                    <label>String</label>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Mapa de integração item</label>
    <nameField>
        <displayFormat>ITI-{000000000}</displayFormat>
        <label>Nome de Mapa de integração item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapa de integração items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/classes/integ_JSONTransformer.cls
public with sharing class integ_JSONTransformer extends TransformerAbstract {
	
	public class integ_JSONTransformerException extends Exception {}
	
	/*
		Converts JSON data to List<SObject>
	*/
	public override List<SObject> convertToSObjectList(IntegrationMap__c integrationMap, String jsonData) {
		system.debug('transformer:');
        system.debug('integration map items: '+integrationMap.IntegrationMapItems__r);
        system.debug('jsonData: '+jsonData);
		List<Object> rawObjList = (List<Object>)JSON.deserializeUntyped(jsonData);
		List<SObject> sObjectRecordList = new List<SObject>();
		
		List<SObject> recordList = new List<SObject>();

		//load custom object fields
		Schema.sObjectType sObjectType = Schema.getGlobalDescribe().get(integrationMap.SObjectApiNameTxt__c);

		Map <String, Schema.SObjectField> sObjectFieldMap = sObjectType.getDescribe()
																.fields
																.getMap();
        system.debug('sobjectfieldmap: '+sObjectFieldMap);
		
		//row number
		Integer rowNumber = 1;
		
		//iterate over each json record
		for (Object obj : rawObjList) {
			
			//cast json data record to map
			Map<String, Object> recordFieldMap = (Map<String, Object>)obj;
			
			//create a new custom object instance
			SObject sObjectRecord = sObjectType.newSObject();
			
			//iterate over each json field
			for (IntegrationMapItem__c fieldMapItem : integrationMap.IntegrationMapItems__r) {
				//system.debug('fieldmapitem atual: '+fieldMapItem);
				if (!fieldMapItem.IsActive__c) {
					continue;
				}
				
				
				//get json data
				Object fieldValue = recordFieldMap.get(fieldMapItem.ExternalFieldNameTxt__c);
				
				try {
					
					/*
					
						It just support String data attributes like:
						
						{
							attr : 'value'
						}
						
						
						In another moment we need to support 
						Object data atrributest like: 
						
						{  
							attr : { 
								attr: 'value' 
							}
						}
					
					*/
					
					if (fieldValue instanceof String  || (fieldValue == null)) {
						
						//if value is null set default as value
						if ((fieldValue == null || fieldValue == '')) {
							fieldValue = fieldMapItem.DefaultValueTxt__c; 
						}
						
						//if has no value and field is mandatory
						//throw error
						if ((fieldValue == null || fieldValue == '') && fieldMapItem.IsRequired__c) {
							throw new integ_JSONTransformerException(fieldMapItem.InternalFieldNameTxt__c + ' can\"t be null it is required for ' + integrationMap.Name);
						}
						
						//todo validate if TypeTxt is ok
						integ_IFieldCast fieldCastImpl = this.getFieldCastImpl(fieldMapItem.TypeTxt__c);
						Object result = fieldCastImpl.getValue(sObjectFieldMap, recordFieldMap, fieldMapItem, fieldValue);
						//system.debug('resulto: '+result);
                        //system.debug('campo: '+sObjectFieldMap.get(fieldMapItem.InternalFieldNameTxt__c));
						if (result instanceof SObject) {
							Schema.sObjectField field = sObjectFieldMap.get(fieldMapItem.InternalFieldNameTxt__c);
							Schema.DescribeFieldResult fieldDescribe = field.getDescribe();
							sObjectRecord.putSObject(fieldDescribe.getRelationshipName(), (SObject)result);
						} else { 
                            //ALTERADO
                            if(!sObjectFieldMap.get(fieldMapItem.InternalFieldNameTxt__c).getDescribe().isAutoNumber()){
                                //AQUI ERA ONDE ESTAVA DANDO ERRO AO ASSOCIAR UMA STRING A UM CAMPO AUTONUMBER
                                sObjectRecord.put(fieldMapItem.InternalFieldNameTxt__c, result);
                            }else{
                                system.debug('entrou');
                            }
						}

        				System.debug(LoggingLevel.FINEST, '*** ' + fieldMapItem.InternalFieldNameTxt__c + ' -> ' 
        					+ fieldMapItem.ExternalFieldNameTxt__c + ' = [' + result + ']');

					}
					
				} catch(Exception ex) {
					throw new integ_FieldCastException(ex, fieldMapItem.InternalFieldNameTxt__c, fieldMapItem.TypeTxt__c, ex.getMessage(), rowNumber);
				}
				
			}
			
			rowNumber++;
			
			recordList.add(sObjectRecord);
		}
		
		return recordList;
		
	}
	
	public override String convertToRawData(List<SObject> sObjectRecordList) {
		return JSON.serialize(sObjectRecordList);
	}		
		
}