Integration_Examples/Inbound_Mexichem/objects/IntegrationMapItem__c.object
<CustomObject>
    <description>[a08][IntegrationMapItem__c] Mapa de integração item.</description>
    <fields>
        <fullName>InternalFieldNameTxt__c</fullName>
        <label>Campo interno</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedObjectExternalIdTxt__c</fullName>
        <label>Id externo do objeto relacionado</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapa de integração item</label>
    <nameField>
        <displayFormat>ITI-{000000000}</displayFormat>
        <label>Nome de Mapa de integração item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapa de integração items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/classes/integ_FieldCastLookup.cls
public with sharing class integ_FieldCastLookup implements integ_IFieldCast {

    public Object getValue(Map <String, Schema.SObjectField> sObjectFieldMap, Map<String, Object> recordFieldMap, 
    	IntegrationMapItem__c fieldMapItem, Object fieldValue) { 
    		
    		SObject childObject = null;
			Schema.sObjectField field = sObjectFieldMap.get(fieldMapItem.InternalFieldNameTxt__c);
			
			if (field != null) {
				
				Schema.DescribeFieldResult fieldDescribe = field.getDescribe();
				childObject = fieldDescribe.getReferenceTo()[0].newSObject();

				System.debug('*** ' + field + childObject);
				System.debug('*** fieldDescribe' + fieldDescribe + childObject);
				System.debug('*** fieldMapItem.RelatedObjectExternalIdTxt__c' + fieldMapItem.RelatedObjectExternalIdTxt__c);
				
				if (fieldValue != null) {
					childObject.put(fieldMapItem.RelatedObjectExternalIdTxt__c, String.valueOf(fieldValue));
				} else {
					return null;
				}
			}
			
			return childObject;
    	}
    
}