Integration_Examples/Inbound_Mexichem/objects/IntegrationMapItem__c.object
<CustomObject>
    <description>[a08][IntegrationMapItem__c] Mapa de integração item.</description>
    <fields>
        <fullName>ExternalFieldNameTxt__c</fullName>
        <label>Campo externo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapa de integração item</label>
    <nameField>
        <displayFormat>ITI-{000000000}</displayFormat>
        <label>Nome de Mapa de integração item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapa de integração items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/classes/integ_SAPDateToSfFormula.cls
public with sharing class integ_SAPDateToSfFormula implements IFormulaField {
	public Object resolve(IntegrationMapItem__c item, Map<String, Object> externalDataMap) {
		
		String dateString = (String) externalDataMap.get(item.ExternalFieldNameTxt__c);
		
		//when date is null sap send 00000000
		//so if date is 00000000
		if (dateString == '00000000') {
			return null;
		} else if (dateString == null) {
			return null;
		} else if (dateString == '') {
			return null;
		}
		
		//System.debug('sap date: ' + dateString);
		
		String year = dateString.substring(0,4);
		String month = dateString.substring(4,6);
		String day = dateString.substring(6,8);
		
		return Date.newInstance(Integer.valueOf(year), Integer.valueOf(month), Integer.valueOf(day));
		
	}
}