Integration_Examples/Inbound_Mexichem/objects/IntegrationMapItem__c.object
<CustomObject>
    <description>[a08][IntegrationMapItem__c] Mapa de integração item.</description>
    <fields>
        <fullName>FormulaClassName__c</fullName>
        <label>Nome da classe da fórmula</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InternalFieldNameTxt__c</fullName>
        <label>Campo interno</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedObjectExternalIdTxt__c</fullName>
        <label>Id externo do objeto relacionado</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapa de integração item</label>
    <nameField>
        <displayFormat>ITI-{000000000}</displayFormat>
        <label>Nome de Mapa de integração item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapa de integração items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/classes/integ_FieldCastLookupFormula.cls
public with sharing class integ_FieldCastLookupFormula implements integ_IFieldCast {
    
    public Object getValue(Map <String, Schema.SObjectField> sObjectFieldMap, Map<String, Object> recordFieldMap, 
    	IntegrationMapItem__c fieldMapItem, Object fieldValue) { 
		
		Schema.sObjectField field = sObjectFieldMap.get(fieldMapItem.InternalFieldNameTxt__c);
		Schema.DescribeFieldResult fieldDescribe = field.getDescribe();
		
		Type formulaClass = Type.forName(fieldMapItem.FormulaClassName__c);
									IFormulaField formulaField = (IFormulaField)formulaClass.newInstance();
		
		SObject childObject = fieldDescribe.getReferenceTo()[0].newSObject();
		
		Object result = formulaField.resolve(fieldMapItem, recordFieldMap);
		
		if (result != null) {
			childObject.put(fieldMapItem.RelatedObjectExternalIdTxt__c, result);
		} else {
			childObject = null;
		}
		
		return childObject;
		
    }
    
}