Integration_Examples/Inbound_Mexichem/objects/IntegrationMap__c.object
<CustomObject>
    <description>[a09][IntegrationMap__c] Mapa de integração.</description>
    <fields>
        <fullName>CommandClassName__c</fullName>
        <defaultValue>&quot;GenericIntegrationService&quot;</defaultValue>
        <label>Classe de comando</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomOperationClassName__c</fullName>
        <label>Nome da classe da operação customizada</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DMLOperationTxt__c</fullName>
        <label>Operação</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Insert</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Upsert</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntegrationId__c</fullName>
        <label>ID da integração</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OutputDataTypeTxt__c</fullName>
        <label>Tipo de dado de entrada</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CSV</fullName>
                </value>
                <value>
                    <fullName>JSON</fullName>
                    <default>true</default>
                    <label>JSON</label>
                </value>
                <value>
                    <fullName>XML</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SObjectApiNameTxt__c</fullName>
        <label>API name do objeto</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Mapa de integração</label>
    <nameField>
        <label>Integração</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapas de integração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/objects/IntegrationMapItem__c.object
<CustomObject>
    <description>[a08][IntegrationMapItem__c] Mapa de integração item.</description>
    <fields>
        <fullName>ExternalFieldNameTxt__c</fullName>
        <label>Campo externo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntegrationMap__c</fullName>
        <label>Mapa de integração</label>
        <referenceTo>IntegrationMap__c</referenceTo>
        <relationshipLabel>Mapa de integração items</relationshipLabel>
        <relationshipName>IntegrationMapItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>InternalFieldNameTxt__c</fullName>
        <label>Campo interno</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTxt__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Decimal</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>Lookup Formula</fullName>
                </value>
                <value>
                    <fullName>String</fullName>
                    <default>true</default>
                    <label>String</label>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Mapa de integração item</label>
    <nameField>
        <displayFormat>ITI-{000000000}</displayFormat>
        <label>Nome de Mapa de integração item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapa de integração items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/classes/ZTinteg_JSONTransformer.cls
@isTest
public class ZTinteg_JSONTransformer {
    
    public static testmethod void productImport(){
        
        IntegrationMap__c integ = new IntegrationMap__c(
        	Name = 'Integração de Produto',
            IntegrationId__c = 'SYNC_PRODUCT_INBOUND',
            SObjectApiNameTxt__c = 'Product2',
            DMLOperationTxt__c = 'Custom',
            CustomOperationClassName__c = 'integ_CustomOperationProduct',
            CommandClassName__c = 'GenericIntegrationService',
            OutputDataTypeTxt__c  = 'JSON'
        );
        insert integ;
        
        IntegrationMapItem__c integItem = new IntegrationMapItem__c(
            IntegrationMap__c = integ.Id,
            TypeTxt__c  = 'String',
            InternalFieldNameTxt__c = 'ProductCodeTxt__c',
            ExternalFieldNameTxt__c = 'MATNR'
        );
        insert integItem;
        
        
        Test.startTest();
        
        WSInBoundOrquestration.WSInBoundOrquestrationVO vo = new WSInBoundOrquestration.WSInBoundOrquestrationVO();
        vo.integrationId = 'SYNC_PRODUCT_INBOUND';
        vo.content = '[{"MAKTX":"FITA VIDEO","BREIT":"0.000 ","BRGEW":"0.149 ","EAN11":"","GEWEI":"KG","HOEHE":"0.000 ","LAENG":"0.000 ","MATNR":"000000000000001010","MEINS":"ST","NTGEW":"0.149 ","SPART":""}]';
        vo.isSync = true;
        
        WSInBoundOrquestration.executePost(vo);
        
        integ_JSONTransformer transf = new integ_JSONTransformer();
        transf.convertToRawData(new List<Contact>{});
        
        Test.stopTest();
        
    }
    
}