Integration_Examples/Inbound_Mexichem/objects/IntegrationMap__c.object
<CustomObject>
    <description>[a09][IntegrationMap__c] Mapa de integração.</description>
    <label>Mapa de integração</label>
    <nameField>
        <label>Integração</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapas de integração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/objects/IntegrationMapItem__c.object
<CustomObject>
    <description>[a08][IntegrationMapItem__c] Mapa de integração item.</description>
    <fields>
        <fullName>ExternalFieldNameTxt__c</fullName>
        <label>Campo externo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntegrationMap__c</fullName>
        <label>Mapa de integração</label>
        <referenceTo>IntegrationMap__c</referenceTo>
        <relationshipLabel>Mapa de integração items</relationshipLabel>
        <relationshipName>IntegrationMapItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Mapa de integração item</label>
    <nameField>
        <displayFormat>ITI-{000000000}</displayFormat>
        <label>Nome de Mapa de integração item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapa de integração items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Integration_Examples/Inbound_Mexichem/classes/ZTinteg_SAPDateToSfFormula.cls
@isTest
private class ZTinteg_SAPDateToSfFormula {
    static testMethod void testAll() {
    	
    	IntegrationMap__c integrationMap = ULTestData.createIntegrationMap('Integração XXX', 'Contact', 'GenericIntegrationService', 'eventName', 'Insert', '', 'CSV');
    	insert integrationMap;
    	
    	IntegrationMapItem__c integrationMapItem1 = ULTestData.createIntegrationMapItem(integrationMap.Id, 'Data', 'date', 'String');
    	insert integrationMapItem1;
    	
    	Map<String, Object> mapa1 = new Map<String, Object>(); 
    	mapa1.put(integrationMapItem1.ExternalFieldNameTxt__c, '20160506');
    	    	
    	System.Test.startTest();
    	
    	integ_SAPDateToSfFormula formula = new integ_SAPDateToSfFormula();
    	formula.resolve(integrationMapItem1, mapa1);
    	
    	System.Test.stopTest();
    	
    }
}