Log Interface/objects/LogInterface__c.object
<CustomObject>
    <label>LogInterface</label>
    <nameField>
        <label>LogInterface Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LogInterfaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Log Interface/objects/LogInterfaceItem__c.object
<CustomObject>
    <fields>
        <fullName>LogInterface__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LogInterface</label>
        <referenceTo>LogInterface__c</referenceTo>
        <relationshipLabel>LogInterfaceItems</relationshipLabel>
        <relationshipName>LogInterfaceItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LogInterfaceItem</label>
    <nameField>
        <label>LogInterfaceItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LogInterfaceItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Log Interface/classes/LogInterfaceItemBO.cls
/* 
------------------------------------------------------------------------------------------------
-- - Name   : LogInterfaceItemBO 
-- - Company: CSC 
-- - Author : José Miguel Paschoa Junior 
-- - Description : Classe que contém a regra de negócio de LogInterfaceItem__c
-- -- Date         Name                              Version    Remarks 
------------------------------------------------------------------------------------------------ 
-- -- 19-08-2015   José Miguel Paschoa Junior        1.0        Initial version 
-- -- 09-09-2015   Camila Stoppa Vicente             1.1        Ajuste do código e revisão
------------------------------------------------------------------------------------------------
*/
	public with sharing class LogInterfaceItemBO {
//	    private static final LogInterfaceItemBO instance = new LogInterfaceItemBO();
//	    /** Private constructor to prevent the creation of instances of this class.*/
//	    private LogInterfaceItemBO(){}
//	    
//	    /**
//	    * Method responsible for providing the instance of this class.
//	    * @return LogInterfaceItemBO instance.
//	    */
//	    public static LogInterfaceItemBO getInstance() {
//	        return instance;
//	    }
//	    
//	    /**
//	    * Method responsible for insert of Logs Items.
//	    * @param list of Object LogInterfaceItem__c.
//	    */
//	    public void insertLogItem(List<LogInterfaceItem__c> logs) {
//	        LogInterfaceItemDAO.getInstance().insertLogItem(logs);
//	    }
//	    
//	    /**
//	    * Method responsible for insert a Logs Items.
//	    * @param list of Object LogInterfaceItem__c.
//	    */
//	    public void insertLogItem(LogInterfaceItem__c log) {
//	        List<LogInterfaceItem__c> items = new List<LogInterfaceItem__c>();
//	        items.add(log);
//	        insertLogItem(items);
//	    }    
//	    
//	    /**
//	    * Method responsible for search the last Log Item.
//	    * @param Id of object LogInterface__c.
//	    * @return list of object LogInterfaceItem__c.
//	    */
//	    public List<LogInterfaceItem__c> lastInsertedRecord(Id logInter){
//	        return LogInterfaceItemDAO.getInstance().lastInsertedRecord(logInter);
//	    }
	}