Log Interface/objects/LogInterface__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FailQuantity__c</fullName>
        <label>Fail Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interface__c</fullName>
        <label>Interface</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SuccessQuantity__c</fullName>
        <label>SuccessQuantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalQuantity__c</fullName>
        <label>TotalQuantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>LogInterface</label>
    <nameField>
        <label>LogInterface Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LogInterfaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Log Interface/classes/LogInterfaceDAO.cls
/* 
------------------------------------------------------------------------------------------------
-- - Name   : LogInterfaceDAO 

------------------------------------------------------------------------------------------------
*/
public with sharing class LogInterfaceDAO {
	private static final LogInterfaceDAO instance = new LogInterfaceDAO();
	/** Private constructor to prevent the creation of instances of this class.*/
	private LogInterfaceDAO(){}

	/**
	* Method responsible for providing the instance of this class.
	* @return LogInterfaceDAO instance.
	*/
	public static LogInterfaceDAO getInstance(){
		return instance;
	}

    /**
    * Method responsible for making upsert of Logs.
    * @param Object LogInterface__c.
    */
	public void upsertLog(LogInterface__c log){
		Database.upsert(log);
	}
    

    /**
    * Method responsible for insert of Logs.
    * @param Object LogInterface__c.
    */        
	public void insertRecord(LogInterface__c log) {
		Database.insert(log);
	}    

    /**
    * Method responsible for retrieve LogInterface__c.
    * @param Id of RecordTypeId of object LogInterface__c.
    * @return object LogInterface__c.
    */
	public LogInterface__c getRecord(Id id) {
		return [	SELECT 		Id, 
                				Date__c, 
                				Name, 
                				Interface__c, 
                				FailQuantity__c, 
                				SuccessQuantity__c,
                				Status__c,
                				TotalQuantity__c
			   		FROM 		LogInterface__c 
					WHERE 		Id =: id
					ORDER BY 	CreatedDate DESC 
                	LIMIT 1];
	}
}