CloneManager/objects/Clone_Manager__mdt.object
<CustomObject>
    <fields>
        <fullName>Child_Columns_Fieldset__c</fullName>
        <description>Store the name of the fieldset that determines the columns to be shown on the Clone Manager component. Defaults to Name only</description>
        <label>Child Columns Fieldset</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_Object_FieldSet__c</fullName>
        <inlineHelpText>Optional : Field-set is used for the related object to only clone specific fields. If left blank it is going to run a deep clone for the related object.</inlineHelpText>
        <label>Child Object FieldSet</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_Object__c</fullName>
        <inlineHelpText>Enter child object API name.</inlineHelpText>
        <label>Child Object</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Lookup_Field__c</fullName>
        <inlineHelpText>Enter the parent lookup field API name from the child object.</inlineHelpText>
        <label>Parent Lookup Field</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Object__c</fullName>
        <inlineHelpText>Enter parent object API name.</inlineHelpText>
        <label>Parent Object</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Clone Manager</label>
    <pluralLabel>Clone Managers</pluralLabel>
</CustomObject>

CloneManager/classes/CloneManagerDao.cls
/*
Name: CloneManagerDao
Author: Sandeep Kumar (Siemens) and Guilherme Oliveira (Harpia Cloud)
Date: 2019.10.15
Description: Custom clone with related class for cloning objects with custom related objects
TestClass: CloneManagerTest
*/

public class CloneManagerDao{
 
    public Schema.sObjectType reterieveSObjectType(String recordId){        
        return Id.valueOf(recordId).getSObjectType();
    }
    
    public List<Clone_Manager__mdt> retrieveRelatedObject(String parentObjectAPIName){
        
        return [SELECT 
                Id, 
                Child_Object__c,
                Child_Object_FieldSet__c,
                Parent_Lookup_Field__c,
                Parent_Object__c,
                Child_Columns_Fieldset__c
                FROM Clone_Manager__mdt 
                WHERE IsActive__c = true AND
                Parent_Object__c =:parentObjectAPIName];
    }
    
    public List<SObject> queryAllData(String fields,String childObject,String parentLookupField,String recordId){
        String finalQuery = 'SELECT ' + fields + ' FROM '+childObject+' WHERE '+parentLookupField+' =:recordId ORDER BY Name ASC';
        return Database.query(finalQuery);
    }
    
    

}